#设置提供的服务名
spring:
  application:
    name: wechatweb-service-base
  #配置数据库
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://rm-wz9utdf0ilyfd5j612o.mysql.rds.aliyuncs.com:3306/wechatweb?useUnicode=true&characterEncoding=utf8
    username: root
    password: sunSUN19980928
  # 定位模板的目录
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cash: false
  devtools:
    restart:
      enabled: true
#spring.devtools.restart.enabled: true

#设置自己启动的端口
server:
  port: 5000
  address: 0.0.0.0


#mybatis plus
mybatis-plus:
  #sql日志打印
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #指明mapper.xml扫描位置(classpath* 代表编译后类文件根目录)
  mapper-locations: classpath*:/mapper/**Mapper.xml
  #指明实体扫描(多个package用逗号或者分号分隔)
  typeAliasesPackage: javademo.tyh.model.base;javademo.tyh.model.hotel;
  global-config:
    #主键类型 0:数据库ID自增, 1:用户输入ID,2:全局唯一ID (数字类型唯一ID), 3:全局唯一ID UUID
    id-type: 0
    #字段策略(拼接sql时用于判断属性值是否拼接) 0:忽略判断,1:非NULL判断,2:非空判断
    field-strategy: 2
    #驼峰下划线转换含查询column及返回column(column下划线命名create_time，返回java实体是驼峰命名createTime，开启后自动转换否则保留原样)
    db-column-underline: true
    #是否动态刷新mapper
    refresh-mapper: false
wechat:
  app-id: wx08988f2cc05f7950
  appsecret: 80ca16ce870d1ff3c661e65c74522bcc
